version: "3"
services:
  backend:
    container_name: mini_back
    image: mini_back_image
    ports:
      - 8080:8080
    volumes:
      - /var/mini:/data
    networks:
      - deploy
    build:
      context: /var/jenkins_home/util/pipeline/ ## build Docker file location
      dockerfile: Dockerfile ## build file name

networks:
  deploy:
    external: true