spring:
  profiles:
    active: dev # local, dev 중 선택

server:
  port: 8080 # 구동 포트
  error: # error code: Exception handler 처리
    include-exception: false
    include-message: always
    include-stacktrace: on_param
    whitelabel:
      enabled: true

  mvc: # Swagger 설정
    path match:
      matching-strategy: ant_path_matcher

springfox: # Swagger: Restful Api 문서 자동화 도구
documentation:
  swagger:
    use-model-v3: false